version: "3"

services:
  caddy:
    image: "caddy"
    volumes:
      - ./certs:/root/certs
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "80:80"
      - "443:443"

networks:
  default:
    external: true
    name: selfhosted
