version: "3"

services:
  homer:
    image: b4bz/homer
    container_name: homer
    volumes:
      - /Users/adam/Development/self-hosted-services/homer/assets:/www/assets
    restart: unless-stopped
    environment:
      INIT_ASSETS: 0

networks:
  default:
    external: true
    name: selfhosted
