version: "3"

services:
  homer:
    image: b4bz/homer
    container_name: homer
    volumes:
      - ~/self-hosted/homer/assets:/www/assets
    ports:
      - 9000:8080
    restart: unless-stopped

networks:
  default:
    external: true
    name: selfhosted
